backend:
  name: github
  repo: QardsJs/qards
  branch: master

publish_mode: editorial_workflow
media_folder: static/assets

collections:
  - name: blog
    label: Blog
    folder: static/content/collections/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }